"""Generated preview type surface for the native ``krishiv`` module."""

from typing import Any

class BlockingSession:
    def collect(self, *args: Any, **kwargs: Any) -> Any: ...
    def connect(self, *args: Any, **kwargs: Any) -> Any: ...
    def embedded(self, *args: Any, **kwargs: Any) -> Any: ...
    def from_env(self, *args: Any, **kwargs: Any) -> Any: ...
    def sql(self, *args: Any, **kwargs: Any) -> Any: ...

class BroadcastContext:
    def emit(self, *args: Any, **kwargs: Any) -> Any: ...

class BroadcastStream:
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_broadcast_process(self, *args: Any, **kwargs: Any) -> Any: ...

class ChangeFeedIter:
    def __aiter__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __anext__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __iter__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __next__(self, *args: Any, **kwargs: Any) -> Any: ...

class Column:
    def __add__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __and__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __bool__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __mul__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __or__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __richcmp__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __sub__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __truediv__(self, *args: Any, **kwargs: Any) -> Any: ...
    def alias(self, *args: Any, **kwargs: Any) -> Any: ...
    def asc(self, *args: Any, **kwargs: Any) -> Any: ...
    def cast(self, *args: Any, **kwargs: Any) -> Any: ...
    def desc(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_not_null(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_null(self, *args: Any, **kwargs: Any) -> Any: ...
    def normalized_ast(self, *args: Any, **kwargs: Any) -> Any: ...
    def over(self, *args: Any, **kwargs: Any) -> Any: ...
    def sql(self, *args: Any, **kwargs: Any) -> Any: ...
    def try_cast(self, *args: Any, **kwargs: Any) -> Any: ...

class ConnectedStreams:
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_co_process(self, *args: Any, **kwargs: Any) -> Any: ...

class DataFrame:
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def alias(self, *args: Any, **kwargs: Any) -> Any: ...
    def boundedness(self, *args: Any, **kwargs: Any) -> Any: ...
    def cache(self, *args: Any, **kwargs: Any) -> Any: ...
    def collect(self, *args: Any, **kwargs: Any) -> Any: ...
    def collect_async(self, *args: Any, **kwargs: Any) -> Any: ...
    def collect_batches(self, *args: Any, **kwargs: Any) -> Any: ...
    def collect_pretty(self, *args: Any, **kwargs: Any) -> Any: ...
    def collect_with_stats(self, *args: Any, **kwargs: Any) -> Any: ...
    def columns(self, *args: Any, **kwargs: Any) -> Any: ...
    def create_or_replace_temp_view(self, *args: Any, **kwargs: Any) -> Any: ...
    def describe(self, *args: Any, **kwargs: Any) -> Any: ...
    def distinct(self, *args: Any, **kwargs: Any) -> Any: ...
    def drop_columns(self, *args: Any, **kwargs: Any) -> Any: ...
    def drop_nulls(self, *args: Any, **kwargs: Any) -> Any: ...
    def except_(self, *args: Any, **kwargs: Any) -> Any: ...
    def except_all(self, *args: Any, **kwargs: Any) -> Any: ...
    def except_distinct(self, *args: Any, **kwargs: Any) -> Any: ...
    def execute_stream_async(self, *args: Any, **kwargs: Any) -> Any: ...
    def explain(self, *args: Any, **kwargs: Any) -> Any: ...
    def explain_logical(self, *args: Any, **kwargs: Any) -> Any: ...
    def explain_mode(self, *args: Any, **kwargs: Any) -> Any: ...
    def fill_null(self, *args: Any, **kwargs: Any) -> Any: ...
    def filter(self, *args: Any, **kwargs: Any) -> Any: ...
    def filter_column(self, *args: Any, **kwargs: Any) -> Any: ...
    def group_by(self, *args: Any, **kwargs: Any) -> Any: ...
    def group_by_columns(self, *args: Any, **kwargs: Any) -> Any: ...
    def intersect(self, *args: Any, **kwargs: Any) -> Any: ...
    def intersect_distinct(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_bounded(self, *args: Any, **kwargs: Any) -> Any: ...
    def join(self, *args: Any, **kwargs: Any) -> Any: ...
    def join_on(self, *args: Any, **kwargs: Any) -> Any: ...
    def limit(self, *args: Any, **kwargs: Any) -> Any: ...
    def num_rows(self, *args: Any, **kwargs: Any) -> Any: ...
    def order_by(self, *args: Any, **kwargs: Any) -> Any: ...
    def persist(self, *args: Any, **kwargs: Any) -> Any: ...
    def pivot(self, *args: Any, **kwargs: Any) -> Any: ...
    def rename(self, *args: Any, **kwargs: Any) -> Any: ...
    def repartition(self, *args: Any, **kwargs: Any) -> Any: ...
    def sample(self, *args: Any, **kwargs: Any) -> Any: ...
    def schema(self, *args: Any, **kwargs: Any) -> Any: ...
    def select(self, *args: Any, **kwargs: Any) -> Any: ...
    def select_columns(self, *args: Any, **kwargs: Any) -> Any: ...
    def select_exprs(self, *args: Any, **kwargs: Any) -> Any: ...
    def show(self, *args: Any, **kwargs: Any) -> Any: ...
    def sort(self, *args: Any, **kwargs: Any) -> Any: ...
    def to_streaming(self, *args: Any, **kwargs: Any) -> Any: ...
    def union(self, *args: Any, **kwargs: Any) -> Any: ...
    def union_distinct(self, *args: Any, **kwargs: Any) -> Any: ...
    def unpersist(self, *args: Any, **kwargs: Any) -> Any: ...
    def unpivot(self, *args: Any, **kwargs: Any) -> Any: ...
    def with_column(self, *args: Any, **kwargs: Any) -> Any: ...
    def write_csv(self, *args: Any, **kwargs: Any) -> Any: ...
    def write_csv_with_options(self, *args: Any, **kwargs: Any) -> Any: ...
    def write_file(self, *args: Any, **kwargs: Any) -> Any: ...
    def write_json(self, *args: Any, **kwargs: Any) -> Any: ...
    def write_parquet(self, *args: Any, **kwargs: Any) -> Any: ...
    def write_parquet_with_options(self, *args: Any, **kwargs: Any) -> Any: ...
    def write_stream(self, *args: Any, **kwargs: Any) -> Any: ...

class DataFrameStream:
    def __aiter__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __anext__(self, *args: Any, **kwargs: Any) -> Any: ...

class DataStreamReader:
    def file_stream(self, *args: Any, **kwargs: Any) -> Any: ...

class DataStreamWriter:
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def foreach_batch(self, *args: Any, **kwargs: Any) -> Any: ...
    def option(self, *args: Any, **kwargs: Any) -> Any: ...
    def output_mode(self, *args: Any, **kwargs: Any) -> Any: ...
    def query_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def start(self, *args: Any, **kwargs: Any) -> Any: ...
    def trigger(self, *args: Any, **kwargs: Any) -> Any: ...

class GroupedDataFrame:
    def agg(self, *args: Any, **kwargs: Any) -> Any: ...
    def agg_columns(self, *args: Any, **kwargs: Any) -> Any: ...
    def agg_grouping_sets(self, *args: Any, **kwargs: Any) -> Any: ...
    def count(self, *args: Any, **kwargs: Any) -> Any: ...
    def cube(self, *args: Any, **kwargs: Any) -> Any: ...
    def rollup(self, *args: Any, **kwargs: Any) -> Any: ...

class HudiWriteResult:
    def instant(self, *args: Any, **kwargs: Any) -> Any: ...
    def rows_inserted(self, *args: Any, **kwargs: Any) -> Any: ...
    def rows_updated(self, *args: Any, **kwargs: Any) -> Any: ...
    def snapshot_rows(self, *args: Any, **kwargs: Any) -> Any: ...

class IcebergRestCatalog:
    def list_tables(self, *args: Any, **kwargs: Any) -> Any: ...
    def load_table_metadata(self, *args: Any, **kwargs: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class InMemoryVectorSink:
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_by_ids(self, *args: Any, **kwargs: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def query_nearest(self, *args: Any, **kwargs: Any) -> Any: ...
    def sink_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def upsert_batch(self, *args: Any, **kwargs: Any) -> Any: ...

class JobStatus:
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def id(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def state(self, *args: Any, **kwargs: Any) -> Any: ...

class KeyedStream:
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def _repr_html_(self, *args: Any, **kwargs: Any) -> Any: ...
    def connect(self, *args: Any, **kwargs: Any) -> Any: ...
    def session_window_ms(self, *args: Any, **kwargs: Any) -> Any: ...
    def sliding_window_ms(self, *args: Any, **kwargs: Any) -> Any: ...
    def tumbling_window(self, *args: Any, **kwargs: Any) -> Any: ...
    def tumbling_window_ms(self, *args: Any, **kwargs: Any) -> Any: ...
    def window(self, *args: Any, **kwargs: Any) -> Any: ...
    def with_multi_source_watermark(self, *args: Any, **kwargs: Any) -> Any: ...

class ListState:
    def add_json(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def key(self, *args: Any, **kwargs: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class LiveTable:
    def change_feed(self, *args: Any, **kwargs: Any) -> Any: ...
    def drop(self, *args: Any, **kwargs: Any) -> Any: ...
    def ingest_row(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def refresh(self, *args: Any, **kwargs: Any) -> Any: ...

class MapState:
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def key(self, *args: Any, **kwargs: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def put_json(self, *args: Any, **kwargs: Any) -> Any: ...

class MemoCacheInfo:
    ...

class MemoryLakehouseTable:
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def append(self, *args: Any, **kwargs: Any) -> Any: ...
    def current_snapshot_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_where(self, *args: Any, **kwargs: Any) -> Any: ...
    def evolve_schema(self, *args: Any, **kwargs: Any) -> Any: ...
    def merge(self, *args: Any, **kwargs: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def overwrite(self, *args: Any, **kwargs: Any) -> Any: ...
    def update_where(self, *args: Any, **kwargs: Any) -> Any: ...

class MultiSourceWatermarkSpec:
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_source(self, *args: Any, **kwargs: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def with_source_id_column(self, *args: Any, **kwargs: Any) -> Any: ...

class OperationRegistry:
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def cancel(self, *args: Any, **kwargs: Any) -> Any: ...
    def cancelled_ids(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_cancelled(self, *args: Any, **kwargs: Any) -> Any: ...
    def progress(self, *args: Any, **kwargs: Any) -> Any: ...
    def remove(self, *args: Any, **kwargs: Any) -> Any: ...

class ParquetSink:
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def path(self, *args: Any, **kwargs: Any) -> Any: ...

class PreparedStatement:
    def bind(self, *args: Any, **kwargs: Any) -> Any: ...
    def parameter_count(self, *args: Any, **kwargs: Any) -> Any: ...
    def sql(self, *args: Any, **kwargs: Any) -> Any: ...

class ProcessContext:
    def emit(self, *args: Any, **kwargs: Any) -> Any: ...
    def register_event_time_timer(self, *args: Any, **kwargs: Any) -> Any: ...
    def register_processing_time_timer(self, *args: Any, **kwargs: Any) -> Any: ...

class PyQueryResultIter:
    def __iter__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __next__(self, *args: Any, **kwargs: Any) -> Any: ...

class QueryHandle:
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def cancel(self, *args: Any, **kwargs: Any) -> Any: ...
    def collect(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_done(self, *args: Any, **kwargs: Any) -> Any: ...
    def progress(self, *args: Any, **kwargs: Any) -> Any: ...
    def query_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def status(self, *args: Any, **kwargs: Any) -> Any: ...

class QueryResult:
    def __iter__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __len__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def batches(self, *args: Any, **kwargs: Any) -> Any: ...
    def pretty(self, *args: Any, **kwargs: Any) -> Any: ...
    def row_count(self, *args: Any, **kwargs: Any) -> Any: ...
    def show(self, *args: Any, **kwargs: Any) -> Any: ...
    def to_arrow(self, *args: Any, **kwargs: Any) -> Any: ...
    def to_pandas(self, *args: Any, **kwargs: Any) -> Any: ...

class Relation:
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def collect(self, *args: Any, **kwargs: Any) -> Any: ...
    def explain(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_bounded(self, *args: Any, **kwargs: Any) -> Any: ...
    def key_by(self, *args: Any, **kwargs: Any) -> Any: ...
    def session_window(self, *args: Any, **kwargs: Any) -> Any: ...
    def show(self, *args: Any, **kwargs: Any) -> Any: ...
    def sliding_window(self, *args: Any, **kwargs: Any) -> Any: ...
    def to_arrow(self, *args: Any, **kwargs: Any) -> Any: ...
    def to_pandas(self, *args: Any, **kwargs: Any) -> Any: ...
    def tumbling_window(self, *args: Any, **kwargs: Any) -> Any: ...
    def watermark(self, *args: Any, **kwargs: Any) -> Any: ...
    def window(self, *args: Any, **kwargs: Any) -> Any: ...
    def with_event_time(self, *args: Any, **kwargs: Any) -> Any: ...
    def with_source_id_column(self, *args: Any, **kwargs: Any) -> Any: ...
    def with_source_watermark(self, *args: Any, **kwargs: Any) -> Any: ...
    def write_parquet(self, *args: Any, **kwargs: Any) -> Any: ...

class RustScalarUdf:
    def multiply(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...

class ScoredChunk:
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def payload(self, *args: Any, **kwargs: Any) -> Any: ...

class Session:
    def close_unbounded_input(self, *args: Any, **kwargs: Any) -> Any: ...
    def configs(self, *args: Any, **kwargs: Any) -> Any: ...
    def connect(self, *args: Any, **kwargs: Any) -> Any: ...
    def create_temp_view(self, *args: Any, **kwargs: Any) -> Any: ...
    def create_view(self, *args: Any, **kwargs: Any) -> Any: ...
    def dataframe(self, *args: Any, **kwargs: Any) -> Any: ...
    def deregister_table(self, *args: Any, **kwargs: Any) -> Any: ...
    def drop_table(self, *args: Any, **kwargs: Any) -> Any: ...
    def embedded(self, *args: Any, **kwargs: Any) -> Any: ...
    def execute_local(self, *args: Any, **kwargs: Any) -> Any: ...
    def execute_remote(self, *args: Any, **kwargs: Any) -> Any: ...
    def from_bounded_stream(self, *args: Any, **kwargs: Any) -> Any: ...
    def from_env(self, *args: Any, **kwargs: Any) -> Any: ...
    def from_source(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_config(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_streaming_query(self, *args: Any, **kwargs: Any) -> Any: ...
    def jobs(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_aggregate_udfs(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_table_identifiers(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_table_udfs(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_tables(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_udfs(self, *args: Any, **kwargs: Any) -> Any: ...
    def live_table(self, *args: Any, **kwargs: Any) -> Any: ...
    def local(self, *args: Any, **kwargs: Any) -> Any: ...
    def memory_stream(self, *args: Any, **kwargs: Any) -> Any: ...
    def memory_stream_collect(self, *args: Any, **kwargs: Any) -> Any: ...
    def mode(self, *args: Any, **kwargs: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def operation_registry(self, *args: Any, **kwargs: Any) -> Any: ...
    def poll_stream_job(self, *args: Any, **kwargs: Any) -> Any: ...
    def prepare(self, *args: Any, **kwargs: Any) -> Any: ...
    def push_stream_job_input(self, *args: Any, **kwargs: Any) -> Any: ...
    def read_csv(self, *args: Any, **kwargs: Any) -> Any: ...
    def read_csv_with_options(self, *args: Any, **kwargs: Any) -> Any: ...
    def read_file(self, *args: Any, **kwargs: Any) -> Any: ...
    def read_json(self, *args: Any, **kwargs: Any) -> Any: ...
    def read_parquet(self, *args: Any, **kwargs: Any) -> Any: ...
    def read_parquet_with_options(self, *args: Any, **kwargs: Any) -> Any: ...
    def read_stream(self, *args: Any, **kwargs: Any) -> Any: ...
    def register_aggregate_udf(self, *args: Any, **kwargs: Any) -> Any: ...
    def register_function(self, *args: Any, **kwargs: Any) -> Any: ...
    def register_kafka_source(self, *args: Any, **kwargs: Any) -> Any: ...
    def register_parquet(self, *args: Any, **kwargs: Any) -> Any: ...
    def register_parquet_stream(self, *args: Any, **kwargs: Any) -> Any: ...
    def register_record_batches(self, *args: Any, **kwargs: Any) -> Any: ...
    def register_table_udf(self, *args: Any, **kwargs: Any) -> Any: ...
    def register_udf(self, *args: Any, **kwargs: Any) -> Any: ...
    def register_unbounded(self, *args: Any, **kwargs: Any) -> Any: ...
    def register_unbounded_with_capacity(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_config(self, *args: Any, **kwargs: Any) -> Any: ...
    def sql(self, *args: Any, **kwargs: Any) -> Any: ...
    def sql_as(self, *args: Any, **kwargs: Any) -> Any: ...
    def sql_with_timeout(self, *args: Any, **kwargs: Any) -> Any: ...
    def stream(self, *args: Any, **kwargs: Any) -> Any: ...
    def submit_async(self, *args: Any, **kwargs: Any) -> Any: ...
    def submit_stream_job(self, *args: Any, **kwargs: Any) -> Any: ...
    def table(self, *args: Any, **kwargs: Any) -> Any: ...
    def table_exists(self, *args: Any, **kwargs: Any) -> Any: ...
    def table_metadata(self, *args: Any, **kwargs: Any) -> Any: ...
    def unset_config(self, *args: Any, **kwargs: Any) -> Any: ...
    def with_auth_token(self, *args: Any, **kwargs: Any) -> Any: ...
    def with_oidc_provider(self, *args: Any, **kwargs: Any) -> Any: ...
    def with_policy(self, *args: Any, **kwargs: Any) -> Any: ...

class Stream:
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def _repr_html_(self, *args: Any, **kwargs: Any) -> Any: ...
    def broadcast(self, *args: Any, **kwargs: Any) -> Any: ...
    def connect(self, *args: Any, **kwargs: Any) -> Any: ...
    def key_by(self, *args: Any, **kwargs: Any) -> Any: ...
    def session_window_ms(self, *args: Any, **kwargs: Any) -> Any: ...
    def sliding_window_ms(self, *args: Any, **kwargs: Any) -> Any: ...
    def tumbling_window(self, *args: Any, **kwargs: Any) -> Any: ...
    def tumbling_window_ms(self, *args: Any, **kwargs: Any) -> Any: ...
    def watermark(self, *args: Any, **kwargs: Any) -> Any: ...
    def with_multi_source_watermark(self, *args: Any, **kwargs: Any) -> Any: ...
    def with_state_ttl(self, *args: Any, **kwargs: Any) -> Any: ...
    def with_watermark(self, *args: Any, **kwargs: Any) -> Any: ...

class StreamingDataFrame:
    def drop_duplicates(self, *args: Any, **kwargs: Any) -> Any: ...
    def key_by(self, *args: Any, **kwargs: Any) -> Any: ...
    def session_window(self, *args: Any, **kwargs: Any) -> Any: ...
    def sliding_window(self, *args: Any, **kwargs: Any) -> Any: ...
    def tumbling_window(self, *args: Any, **kwargs: Any) -> Any: ...
    def with_event_time(self, *args: Any, **kwargs: Any) -> Any: ...
    def with_side_output(self, *args: Any, **kwargs: Any) -> Any: ...
    def with_watermark_lag(self, *args: Any, **kwargs: Any) -> Any: ...
    def write_stream(self, *args: Any, **kwargs: Any) -> Any: ...

class StreamingQuery:
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def await_termination(self, *args: Any, **kwargs: Any) -> Any: ...
    def id(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_active(self, *args: Any, **kwargs: Any) -> Any: ...
    def last_progress(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def stop(self, *args: Any, **kwargs: Any) -> Any: ...

class StreamingQueryProgress:
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def epoch(self, *args: Any, **kwargs: Any) -> Any: ...
    def input_rows(self, *args: Any, **kwargs: Any) -> Any: ...
    def output_rows(self, *args: Any, **kwargs: Any) -> Any: ...
    def trigger(self, *args: Any, **kwargs: Any) -> Any: ...

class ValueState:
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def key(self, *args: Any, **kwargs: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def set_json(self, *args: Any, **kwargs: Any) -> Any: ...

class WindowedStream:
    def __aiter__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __anext__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def _repr_html_(self, *args: Any, **kwargs: Any) -> Any: ...
    def agg(self, *args: Any, **kwargs: Any) -> Any: ...
    def collect(self, *args: Any, **kwargs: Any) -> Any: ...
    def session_gap_ms(self, *args: Any, **kwargs: Any) -> Any: ...
    def slide_ms(self, *args: Any, **kwargs: Any) -> Any: ...
    def try_next(self, *args: Any, **kwargs: Any) -> Any: ...
    def tumbling_window(self, *args: Any, **kwargs: Any) -> Any: ...
    def window_kind(self, *args: Any, **kwargs: Any) -> Any: ...
    def window_size_ms(self, *args: Any, **kwargs: Any) -> Any: ...

def apply_process_function(*args: Any, **kwargs: Any) -> Any: ...
def apply_state_migration(*args: Any, **kwargs: Any) -> Any: ...
def avg(*args: Any, **kwargs: Any) -> Any: ...
def call_function(*args: Any, **kwargs: Any) -> Any: ...
def col(*args: Any, **kwargs: Any) -> Any: ...
def count(*args: Any, **kwargs: Any) -> Any: ...
def count_all(*args: Any, **kwargs: Any) -> Any: ...
def expr(*args: Any, **kwargs: Any) -> Any: ...
def interval_join(*args: Any, **kwargs: Any) -> Any: ...
def lit(*args: Any, **kwargs: Any) -> Any: ...
def make_example_batch(*args: Any, **kwargs: Any) -> Any: ...
def max(*args: Any, **kwargs: Any) -> Any: ...
def memo_cache_info(*args: Any, **kwargs: Any) -> Any: ...
def memo_transform_call(*args: Any, **kwargs: Any) -> Any: ...
def min(*args: Any, **kwargs: Any) -> Any: ...
def read_delta(*args: Any, **kwargs: Any) -> Any: ...
def read_hudi(*args: Any, **kwargs: Any) -> Any: ...
def read_iceberg(*args: Any, **kwargs: Any) -> Any: ...
def read_kafka(*args: Any, **kwargs: Any) -> Any: ...
def read_kinesis(*args: Any, **kwargs: Any) -> Any: ...
def read_parquet(*args: Any, **kwargs: Any) -> Any: ...
def read_pulsar(*args: Any, **kwargs: Any) -> Any: ...
def register_state_migration(*args: Any, **kwargs: Any) -> Any: ...
def schema_registry_confluent(*args: Any, **kwargs: Any) -> Any: ...
def state_migration(*args: Any, **kwargs: Any) -> Any: ...
def stream_table_join(*args: Any, **kwargs: Any) -> Any: ...
def sum(*args: Any, **kwargs: Any) -> Any: ...
def temporal_join(*args: Any, **kwargs: Any) -> Any: ...
def udf(*args: Any, **kwargs: Any) -> Any: ...
def write_hudi_append(*args: Any, **kwargs: Any) -> Any: ...
def write_hudi_upsert(*args: Any, **kwargs: Any) -> Any: ...
