"""Generated preview type surface for the native ``krishiv`` module."""

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator, Sequence
from contextlib import AbstractContextManager
from typing import Any, Literal, TypeAlias

BatchLike: TypeAlias = "Batch | Any"  # krishiv Batch or pyarrow RecordBatch
ColumnLike: TypeAlias = "Column | str | None | bool | int | float | bytes"
ColumnOrName: TypeAlias = "Column | str"
DataFormat: TypeAlias = Literal["parquet", "csv", "json", "ndjson"]
ExplainMode: TypeAlias = Literal["logical", "physical", "analyze"]
JoinType: TypeAlias = Literal[
    "inner",
    "left",
    "right",
    "full",
    "left_semi",
    "right_semi",
    "left_anti",
    "right_anti",
]
QueryStatusName: TypeAlias = Literal[
    "pending",
    "running",
    "completed",
    "cancelled",
    "failed",
    "consumed",
]
RuntimeMode: TypeAlias = Literal["embedded", "local", "distributed"]
WriteMode: TypeAlias = Literal[
    "error",
    "error_if_exists",
    "append",
    "overwrite",
    "ignore",
    "dynamic_overwrite",
]

class AggExpr:
    def filter(self, *args: object, **kwargs: object) -> object: ...
    def filter_not_null(self, *args: object, **kwargs: object) -> object: ...
    @property
    def function(self) -> object: ...
    @property
    def input_column(self) -> object: ...
    @property
    def output_name(self) -> object: ...

class AggregatingState:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def accumulator_json(self, *args: object, **kwargs: object) -> object: ...
    def add_json(self, *args: object, **kwargs: object) -> object: ...
    def clear(self, *args: object, **kwargs: object) -> object: ...
    def get_result_json(self, *args: object, **kwargs: object) -> object: ...
    def key(self, *args: object, **kwargs: object) -> object: ...

class Batch:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def _repr_html_(self, *args: object, **kwargs: object) -> object: ...
    @property
    def num_columns(self) -> int: ...
    @property
    def num_rows(self) -> int: ...
    def to_arrow(self) -> object: ...
    def to_pandas(self) -> object: ...

class BlockingSession:
    def collect(self, dataframe: DataFrame) -> QueryResult: ...
    @staticmethod
    def connect(coordinator_url: str) -> BlockingSession: ...
    @staticmethod
    def embedded() -> BlockingSession: ...
    @staticmethod
    def from_env() -> BlockingSession: ...
    def sql(self, query: str) -> QueryResult: ...

class BroadcastContext:
    def emit(self, *args: object, **kwargs: object) -> object: ...

class CassandraSink:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def write_batches(self, *args: object, **kwargs: object) -> object: ...

class Column:
    def __add__(self, other: ColumnLike) -> Column: ...
    def __and__(self, other: ColumnLike) -> Column: ...
    def __bool__(self) -> bool: ...
    def __invert__(self, *args: object, **kwargs: object) -> object: ...
    def __mod__(self, *args: object, **kwargs: object) -> object: ...
    def __mul__(self, other: ColumnLike) -> Column: ...
    def __neg__(self, *args: object, **kwargs: object) -> object: ...
    def __or__(self, other: ColumnLike) -> Column: ...
    def __pow__(self, *args: object, **kwargs: object) -> object: ...
    def __radd__(self, *args: object, **kwargs: object) -> object: ...
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def __rmod__(self, *args: object, **kwargs: object) -> object: ...
    def __rmul__(self, *args: object, **kwargs: object) -> object: ...
    def __rsub__(self, *args: object, **kwargs: object) -> object: ...
    def __rtruediv__(self, *args: object, **kwargs: object) -> object: ...
    def __sub__(self, other: ColumnLike) -> Column: ...
    def __truediv__(self, other: ColumnLike) -> Column: ...
    def alias(self, name: str) -> Column: ...
    def asc(self) -> Column: ...
    def astype(self, *args: object, **kwargs: object) -> object: ...
    def between(self, *args: object, **kwargs: object) -> object: ...
    def cast(self, data_type: str) -> Column: ...
    def contains(self, *args: object, **kwargs: object) -> object: ...
    def desc(self) -> Column: ...
    def endswith(self, *args: object, **kwargs: object) -> object: ...
    def eqNullSafe(self, *args: object, **kwargs: object) -> object: ...
    def ilike(self, *args: object, **kwargs: object) -> object: ...
    def isNotNull(self, *args: object, **kwargs: object) -> object: ...
    def isNull(self, *args: object, **kwargs: object) -> object: ...
    def is_not_null(self) -> Column: ...
    def is_null(self) -> Column: ...
    def isin(self, *args: object, **kwargs: object) -> object: ...
    def like(self, *args: object, **kwargs: object) -> object: ...
    def name(self, *args: object, **kwargs: object) -> object: ...
    def normalized_ast(self) -> str: ...
    def not_like(self, *args: object, **kwargs: object) -> object: ...
    def otherwise(self, *args: object, **kwargs: object) -> object: ...
    def over(
        self, partition_by: Sequence[Column] = ..., order_by: Sequence[Column] = ...
    ) -> Column: ...
    def range_between(self, start: int | None, end: int | None) -> Column: ...
    def rlike(self, *args: object, **kwargs: object) -> object: ...
    def rows_between(self, start: int | None, end: int | None) -> Column: ...
    def sql(self) -> str: ...
    def startswith(self, *args: object, **kwargs: object) -> object: ...
    def substr(self, *args: object, **kwargs: object) -> object: ...
    def try_cast(self, data_type: str) -> Column: ...
    def when(self, *args: object, **kwargs: object) -> object: ...

class ConnectorSink:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def kind(self, *args: object, **kwargs: object) -> object: ...
    def write_batches(self, *args: object, **kwargs: object) -> object: ...

class ConnectorSource:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def kind(self, *args: object, **kwargs: object) -> object: ...
    def read_batches(self, *args: object, **kwargs: object) -> object: ...

class DataFrame:
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def _with_ivm_parent(self, *args: object, **kwargs: object) -> object: ...
    def alias(self, name: str) -> DataFrame: ...
    def boundedness(self) -> Literal['bounded', 'unbounded']: ...
    def cache(self) -> DataFrame: ...
    def collect(self) -> QueryResult: ...
    def collect_as_delta_batch(self, *args: object, **kwargs: object) -> object: ...
    async def collect_async(self) -> QueryResult: ...
    def collect_batches(self) -> QueryResult: ...
    def collect_pretty(self) -> str: ...
    def collect_with_stats(self) -> tuple[QueryResult, dict[str, int]]: ...
    def columns(self) -> list[str]: ...
    def create_or_replace_temp_view(self, name: str) -> None: ...
    def describe(self) -> DataFrame: ...
    def distinct(self) -> DataFrame: ...
    def drop_columns(self, columns: Sequence[str]) -> DataFrame: ...
    def drop_nulls(self, columns: Sequence[str] = ...) -> DataFrame: ...
    def except_(self, right: DataFrame) -> DataFrame: ...
    def except_all(self, right: DataFrame) -> DataFrame: ...
    def except_distinct(self, right: DataFrame) -> DataFrame: ...
    async def execute_stream_async(self) -> DataFrameStream: ...
    def explain(self) -> str: ...
    def explain_logical(self) -> str: ...
    def explain_mode(self, mode: ExplainMode = ...) -> str: ...
    def fill_null(self, column: str, value: str) -> DataFrame: ...
    def filter(self, predicate: str) -> DataFrame: ...
    def filter_column(self, predicate: Column) -> DataFrame: ...
    def group_by(self, expressions: Sequence[str]) -> GroupedDataFrame: ...
    def group_by_columns(self, expressions: Sequence[Column]) -> GroupedDataFrame: ...
    def intersect(self, right: DataFrame) -> DataFrame: ...
    def intersect_distinct(self, right: DataFrame) -> DataFrame: ...
    def is_bounded(self) -> bool: ...
    def join(self, right: DataFrame, on: Sequence[str], *, how: JoinType = ...) -> DataFrame: ...
    def join_on(
        self, right: DataFrame, left_on: Sequence[str], right_on: Sequence[str], *, how: JoinType = ...
    ) -> DataFrame: ...
    def limit(self, n: int) -> DataFrame: ...
    def num_rows(self) -> int: ...
    def order_by(self, columns: Sequence[str]) -> DataFrame: ...
    def persist(self) -> DataFrame: ...
    def pivot(
        self,
        groups: Sequence[Column],
        pivot_column: Column,
        aggregate: Column,
        values: Sequence[tuple[Column, str]],
    ) -> DataFrame: ...
    def rename(self, old: str, new: str) -> DataFrame: ...
    def repartition(self, num_partitions: int, key_columns: Sequence[str] = ...) -> DataFrame: ...
    def sample(self, fraction: float) -> DataFrame: ...
    def schema(self) -> list[tuple[str, str]]: ...
    def select(self, columns: Sequence[str]) -> DataFrame: ...
    def select_columns(self, expressions: Sequence[Column]) -> DataFrame: ...
    def select_exprs(self, expressions: Sequence[str]) -> DataFrame: ...
    def show(self, n: int = ...) -> None: ...
    def sort(self, columns: Sequence[str], descending: Sequence[bool] | None = ...) -> DataFrame: ...
    def to_incremental(self, name: str | None = ...) -> IncrementalDataFrame: ...
    def to_streaming(self) -> StreamingDataFrame: ...
    def union(self, right: DataFrame) -> DataFrame: ...
    def union_by_name(self, *args: object, **kwargs: object) -> object: ...
    def union_distinct(self, right: DataFrame) -> DataFrame: ...
    def unnest(self, *args: object, **kwargs: object) -> object: ...
    def unpersist(self) -> None: ...
    def unpivot(self, columns: Sequence[str], name_column: str, value_column: str) -> DataFrame: ...
    def with_column(self, name: str, expression: str) -> DataFrame: ...
    def with_columns_renamed(self, *args: object, **kwargs: object) -> object: ...
    def write_csv(self, path: str) -> None: ...
    def write_csv_with_options(self, path: str, *, delimiter: str | None = ..., has_header: bool | None = ...) -> None: ...
    def write_file(self, path: str, format: DataFormat, *, mode: WriteMode = ..., partition_by: Sequence[str] = ..., max_rows_per_file: int | None = ...) -> None: ...
    def write_json(self, path: str) -> None: ...
    def write_parquet(self, path: str) -> None: ...
    def write_parquet_with_options(self, path: str, *, compression: str | None = ..., max_row_group_size: int | None = ...) -> None: ...
    # ── grafted at import (see krishiv._pyspark) ──
    def selectExpr(self, *exprs: str) -> DataFrame: ...
    def where(self, condition: Column | str) -> DataFrame: ...
    def withColumn(self, name: str, column: ColumnLike) -> DataFrame: ...
    def withColumns(self, columns: dict) -> DataFrame: ...
    def withColumnRenamed(self, existing: str, new: str) -> DataFrame: ...
    def withColumnsRenamed(self, mapping: dict) -> DataFrame: ...
    def drop(self, *cols: ColumnLike) -> DataFrame: ...
    def groupBy(self, *cols: ColumnLike) -> GroupedDataFrame: ...
    def groupby(self, *cols: ColumnLike) -> GroupedDataFrame: ...
    def rollup(self, *cols: ColumnLike) -> Any: ...
    def cube(self, *cols: ColumnLike) -> Any: ...
    def agg(self, *exprs: ColumnLike, **named: ColumnLike) -> DataFrame: ...
    def orderBy(self, *cols: ColumnLike, ascending: object = ...) -> DataFrame: ...
    def dropDuplicates(self, subset: Sequence[str] | None = ...) -> DataFrame: ...
    def drop_duplicates(self, subset: Sequence[str] | None = ...) -> DataFrame: ...
    def unionByName(self, other: DataFrame, allowMissingColumns: bool = ...) -> DataFrame: ...
    def unionAll(self, other: DataFrame) -> DataFrame: ...
    def crossJoin(self, other: DataFrame) -> DataFrame: ...
    def subtract(self, other: DataFrame) -> DataFrame: ...
    def toDF(self, *names: str) -> DataFrame: ...
    def count(self) -> int: ...
    def head(self, n: int | None = ...) -> Any: ...
    def take(self, num: int) -> list: ...
    def first(self) -> Any: ...
    def tail(self, num: int) -> list: ...
    def collect_rows(self) -> list: ...
    def toPandas(self) -> Any: ...
    def toLocalIterator(self) -> Any: ...
    def isEmpty(self) -> bool: ...
    def printSchema(self) -> None: ...
    @property
    def dtypes(self) -> list: ...
    @property
    def na(self) -> Any: ...
    @property
    def stat(self) -> Any: ...
    @property
    def write(self) -> Any: ...
    # The PySpark spelling of the write terminal: `df.to_streaming().write()`.
    @property
    def writeStream(self) -> StreamWriter: ...
    def fillna(self, value: Any, subset: Sequence[str] | None = ...) -> DataFrame: ...
    def dropna(
        self,
        how: str = ...,
        thresh: int | None = ...,
        subset: Sequence[str] | None = ...,
    ) -> DataFrame: ...

class DataFrameStream:
    def __aiter__(self) -> AsyncIterator[Batch]: ...
    async def __anext__(self) -> Batch: ...

class DataStreamReader:
    def file_stream(self, *args: object, **kwargs: object) -> object: ...
    def kafka(self, *args: object, **kwargs: object) -> object: ...

class DeltaBatch:
    def __repr__(self) -> str: ...
    def data_batch(self) -> Batch: ...
    @staticmethod
    def deserialize(data: bytes) -> DeltaBatch: ...
    def drop_zeros(self) -> DeltaBatch: ...
    def filter_negative(self) -> Batch: ...
    def filter_positive(self) -> Batch: ...
    # None only when both sides are omitted (an empty CDC event).
    @staticmethod
    def from_cdc(before: BatchLike | None = ..., after: BatchLike | None = ...) -> DeltaBatch | None: ...
    @staticmethod
    def from_deletes(batch: BatchLike) -> DeltaBatch: ...
    # A record batch carrying one integer weight per row in a trailing
    # `_weight` column: +1 inserts the row, -1 retracts it.
    @staticmethod
    def from_inserts(batch: BatchLike) -> DeltaBatch: ...
    @staticmethod
    def from_update(before: BatchLike, after: BatchLike) -> DeltaBatch: ...
    @staticmethod
    def from_weighted(batch: BatchLike) -> DeltaBatch: ...
    def is_empty(self) -> bool: ...
    def is_insert_only(self) -> bool: ...
    def negate(self) -> DeltaBatch: ...
    @property
    def num_rows(self) -> int: ...
    def serialize(self) -> bytes: ...
    def to_batch(self) -> Batch: ...

class ElasticsearchSink:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def write_batches(self, *args: object, **kwargs: object) -> object: ...

class EngineJobHandle:
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def id(self, *args: object, **kwargs: object) -> object: ...
    def status(self, *args: object, **kwargs: object) -> object: ...

class GroupedDataFrame:
    def agg(self, expressions: Sequence[str]) -> DataFrame: ...
    def agg_columns(self, expressions: Sequence[Column]) -> DataFrame: ...
    def agg_grouping_sets(self, sets: Sequence[Sequence[Column]], aggregates: Sequence[Column]) -> DataFrame: ...
    def count(self) -> DataFrame: ...
    def cube(self, groups: Sequence[Column], aggregates: Sequence[Column]) -> DataFrame: ...
    def rollup(self, groups: Sequence[Column], aggregates: Sequence[Column]) -> DataFrame: ...

class HBaseSink:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def write_batches(self, *args: object, **kwargs: object) -> object: ...

class HudiWriteResult:
    def instant(self, *args: object, **kwargs: object) -> object: ...
    def rows_inserted(self, *args: object, **kwargs: object) -> object: ...
    def rows_updated(self, *args: object, **kwargs: object) -> object: ...
    def snapshot_rows(self, *args: object, **kwargs: object) -> object: ...

class IcebergRestCatalog:
    def list_tables(self, *args: object, **kwargs: object) -> object: ...
    def load_table_metadata(self, *args: object, **kwargs: object) -> object: ...
    def __init__(self, *args: object, **kwargs: object) -> None: ...

class IcebergSink:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def catalog(self, *args: object, **kwargs: object) -> object: ...
    def table(self, *args: object, **kwargs: object) -> object: ...
    def write_batches(self, *args: object, **kwargs: object) -> object: ...

class InMemoryVectorSink:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def delete_by_ids(self, *args: object, **kwargs: object) -> object: ...
    def query_nearest(self, *args: object, **kwargs: object) -> object: ...
    def sink_name(self, *args: object, **kwargs: object) -> object: ...
    def upsert_batch(self, *args: object, **kwargs: object) -> object: ...

class IncrementalDataFrame:
    def __repr__(self) -> str: ...
    def _txn_enter(self) -> None: ...
    def _txn_exit(self, commit: bool) -> StepSummary | None: ...
    # Returns the tick's summary, or None when buffered inside transaction().
    def apply(self, delta: DeltaBatch, source: str | None = ...) -> StepSummary | None: ...
    # Non-consuming peek: repeats, and survives a tick that published nothing.
    def last_output(self) -> DeltaBatch | None: ...
    @property
    def name(self) -> str: ...
    # Each published delta at most once; None if nothing new (coalescing).
    def next_change(self) -> DeltaBatch | None: ...
    def schema_batch(self) -> Batch: ...
    def snapshot(self) -> Batch | None: ...
    @property
    def source_names(self) -> list[str]: ...
    def step(self) -> StepSummary: ...
    # ── grafted at import (see krishiv._pyspark) ──
    def insert(self, batch: BatchLike, source: str | None = ...) -> StepSummary | None: ...
    def delete(self, batch: BatchLike, source: str | None = ...) -> StepSummary | None: ...
    def update(self, before: BatchLike, after: BatchLike, source: str | None = ...) -> StepSummary | None: ...
    def apply_cdc(
        self,
        *,
        before: BatchLike | None = ...,
        after: BatchLike | None = ...,
        source: str | None = ...,
    ) -> StepSummary | None: ...
    def transaction(self) -> AbstractContextManager[IncrementalDataFrame]: ...

class IvmJob:
    def __repr__(self) -> str: ...
    def checkpoint(self) -> bytes: ...
    def checkpoint_delta(self) -> bytes: ...
    def enable_delta_checkpoints(self) -> None: ...
    def enable_input_dedup(self) -> None: ...
    def feed(self, source: str, delta: DeltaBatch) -> None: ...
    def feed_and_step(self, source: str, delta: DeltaBatch) -> StepSummary: ...
    def feed_inserts_and_step(self, source: str, batch: Batch) -> StepSummary: ...
    def feed_snapshot(self, source: str, batches: Sequence[Batch]) -> None: ...
    @property
    def job_id(self) -> str: ...
    def register_view(
        self,
        name: str,
        body_sql: str,
        schema: type,
        is_materialized: bool = ...,
        is_recursive: bool = ...,
    ) -> None: ...
    def register_view_with_lateness(
        self,
        name: str,
        body_sql: str,
        schema: type,
        lateness_ms: dict[str, int],
        is_materialized: bool = ...,
        is_recursive: bool = ...,
    ) -> None: ...
    def restore(self, data: bytes) -> None: ...
    def restore_delta(self, data: bytes) -> None: ...
    def snapshot(self, view: str) -> Batch | None: ...
    def step(self) -> StepSummary: ...

class JobStatus:
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def id(self, *args: object, **kwargs: object) -> object: ...
    def name(self, *args: object, **kwargs: object) -> object: ...
    def state(self, *args: object, **kwargs: object) -> object: ...

class KafkaSink:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def bootstrap_servers(self, *args: object, **kwargs: object) -> object: ...
    def topic(self, *args: object, **kwargs: object) -> object: ...
    def write_batches(self, *args: object, **kwargs: object) -> object: ...

class LanceDbSink:
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def delete_by_ids(self, *args: object, **kwargs: object) -> object: ...
    def open(self, *args: object, **kwargs: object) -> object: ...
    def query_nearest(self, *args: object, **kwargs: object) -> object: ...
    def sink_name(self, *args: object, **kwargs: object) -> object: ...
    def upsert_batch(self, *args: object, **kwargs: object) -> object: ...

class ListState:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def add_json(self, *args: object, **kwargs: object) -> object: ...
    def clear(self, *args: object, **kwargs: object) -> object: ...
    def get_json(self, *args: object, **kwargs: object) -> object: ...
    def key(self, *args: object, **kwargs: object) -> object: ...

class MapState:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def clear(self, *args: object, **kwargs: object) -> object: ...
    def get_map_json(self, *args: object, **kwargs: object) -> object: ...
    def key(self, *args: object, **kwargs: object) -> object: ...
    def put_json(self, *args: object, **kwargs: object) -> object: ...

class MemoCacheInfo:
    @property
    def hits(self) -> object: ...
    @property
    def misses(self) -> object: ...
    @property
    def size(self) -> object: ...

class MemoryLakehouseTable:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def append(self, *args: object, **kwargs: object) -> object: ...
    def current_snapshot_id(self, *args: object, **kwargs: object) -> object: ...
    def delete_where(self, *args: object, **kwargs: object) -> object: ...
    def evolve_schema(self, *args: object, **kwargs: object) -> object: ...
    def merge(self, *args: object, **kwargs: object) -> object: ...
    def overwrite(self, *args: object, **kwargs: object) -> object: ...
    def update_where(self, *args: object, **kwargs: object) -> object: ...

class MemorySink:
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def collect(self, *args: object, **kwargs: object) -> object: ...
    def is_empty(self, *args: object, **kwargs: object) -> object: ...
    def len(self, *args: object, **kwargs: object) -> object: ...

class OperationRegistry:
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def cancel(self, *args: object, **kwargs: object) -> object: ...
    def cancelled_ids(self, *args: object, **kwargs: object) -> object: ...
    def is_cancelled(self, *args: object, **kwargs: object) -> object: ...
    def progress(self, *args: object, **kwargs: object) -> object: ...
    def remove(self, *args: object, **kwargs: object) -> object: ...

class ParquetSink:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def path(self, *args: object, **kwargs: object) -> object: ...

class PgvectorSink:
    def connect(self, *args: object, **kwargs: object) -> object: ...
    def delete_by_ids(self, *args: object, **kwargs: object) -> object: ...
    def query_nearest(self, *args: object, **kwargs: object) -> object: ...
    def sink_name(self, *args: object, **kwargs: object) -> object: ...
    def upsert_batch(self, *args: object, **kwargs: object) -> object: ...

class PineconeSink:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def delete_by_ids(self, *args: object, **kwargs: object) -> object: ...
    def query_nearest(self, *args: object, **kwargs: object) -> object: ...
    def sink_name(self, *args: object, **kwargs: object) -> object: ...
    def upsert_batch(self, *args: object, **kwargs: object) -> object: ...

class Pipeline:
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def expect(self, *args: object, **kwargs: object) -> object: ...
    def flow(self, *args: object, **kwargs: object) -> object: ...
    def mode(self, *args: object, **kwargs: object) -> object: ...
    def refresh(self, *args: object, **kwargs: object) -> object: ...
    def run(self, *args: object, **kwargs: object) -> object: ...
    def sink_memory(self, *args: object, **kwargs: object) -> object: ...
    def source_cdc(self, *args: object, **kwargs: object) -> object: ...
    def source_memory(self, *args: object, **kwargs: object) -> object: ...
    def temp_view(self, *args: object, **kwargs: object) -> object: ...
    def validate(self, *args: object, **kwargs: object) -> object: ...
    def view(self, *args: object, **kwargs: object) -> object: ...

class PreparedStatement:
    def bind(self, *args: object, **kwargs: object) -> object: ...
    def parameter_count(self, *args: object, **kwargs: object) -> object: ...
    def sql(self, *args: object, **kwargs: object) -> object: ...

class ProcessContext:
    def emit(self, *args: object, **kwargs: object) -> object: ...
    def get_state(self, *args: object, **kwargs: object) -> object: ...
    def register_event_time_timer(self, *args: object, **kwargs: object) -> object: ...
    def register_processing_time_timer(self, *args: object, **kwargs: object) -> object: ...
    def set_state(self, *args: object, **kwargs: object) -> object: ...

class PyQueryResultIter:
    def __iter__(self, *args: object, **kwargs: object) -> object: ...
    def __next__(self, *args: object, **kwargs: object) -> object: ...

class QdrantSink:
    def connect(self, *args: object, **kwargs: object) -> object: ...
    def delete_by_ids(self, *args: object, **kwargs: object) -> object: ...
    def query_nearest(self, *args: object, **kwargs: object) -> object: ...
    def sink_name(self, *args: object, **kwargs: object) -> object: ...
    def upsert_batch(self, *args: object, **kwargs: object) -> object: ...

class QueryHandle:
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def cancel(self) -> None: ...
    def collect(self) -> QueryResult: ...
    async def collect_async(self) -> QueryResult: ...
    def is_done(self) -> bool: ...
    def progress(self) -> tuple[int, int]: ...
    def query_id(self) -> int | None: ...
    def status(self) -> QueryStatusName: ...

class QueryResult:
    def __arrow_c_stream__(self, *args: object, **kwargs: object) -> object: ...
    def __iter__(self) -> Iterator[Batch]: ...
    def __len__(self) -> int: ...
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def batches(self) -> list[Batch]: ...
    def pretty(self) -> str: ...
    @property
    def row_count(self) -> int: ...
    def show(self, n: int = ...) -> None: ...
    def to_arrow(self) -> object: ...
    def to_pandas(self) -> object: ...

class Relation:
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def collect(self, *args: object, **kwargs: object) -> object: ...
    def explain(self, *args: object, **kwargs: object) -> object: ...
    def is_bounded(self, *args: object, **kwargs: object) -> object: ...
    def key_by(self, *args: object, **kwargs: object) -> object: ...
    def session_window(self, *args: object, **kwargs: object) -> object: ...
    def show(self, *args: object, **kwargs: object) -> object: ...
    def sliding_window(self, *args: object, **kwargs: object) -> object: ...
    def to_arrow(self, *args: object, **kwargs: object) -> object: ...
    def to_pandas(self, *args: object, **kwargs: object) -> object: ...
    def tumbling_window(self, *args: object, **kwargs: object) -> object: ...
    def watermark(self, *args: object, **kwargs: object) -> object: ...
    def window(self, *args: object, **kwargs: object) -> object: ...
    def with_event_time(self, *args: object, **kwargs: object) -> object: ...
    def with_source_id_column(self, *args: object, **kwargs: object) -> object: ...
    def with_source_watermark(self, *args: object, **kwargs: object) -> object: ...
    def write_parquet(self, *args: object, **kwargs: object) -> object: ...

class RunningJob:
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def id(self, *args: object, **kwargs: object) -> object: ...
    def stop(self, *args: object, **kwargs: object) -> object: ...

class RustScalarUdf:
    def multiply(self, *args: object, **kwargs: object) -> object: ...
    def name(self, *args: object, **kwargs: object) -> object: ...

class Schema:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def __init_subclass__(self, *args: object, **kwargs: object) -> object: ...
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def _repr_html_(self, *args: object, **kwargs: object) -> object: ...
    @classmethod
    def arrow_schema(cls) -> object: ...
    @classmethod
    def column_names(cls) -> list[str]: ...

class SchemaRegistryConfig:
    ...

class ScoredChunk:
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    @property
    def chunk_index(self) -> object: ...
    @property
    def doc_id(self) -> object: ...
    def payload(self, *args: object, **kwargs: object) -> object: ...
    @property
    def score(self) -> object: ...
    @property
    def text(self) -> object: ...

class Session:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def close(self, *args: object, **kwargs: object) -> object: ...
    def close_unbounded_input(self, *args: object, **kwargs: object) -> object: ...
    def configs(self) -> dict[str, str]: ...
    @classmethod
    def connect(cls, url: str, *, grpc_url: str | None = ..., target_parallelism: int | None = ..., shuffle_partitions: int | None = ..., state_ttl_ms: int | None = ...) -> Session: ...
    def create_temp_view(self, *args: object, **kwargs: object) -> object: ...
    def create_view(self, *args: object, **kwargs: object) -> object: ...
    def dataframe(self, batches: Sequence[Batch]) -> DataFrame: ...
    def deregister_table(self, name: str) -> None: ...
    def drop_table(self, name: str) -> None: ...
    @classmethod
    def embedded(cls, *, target_parallelism: int | None = ..., shuffle_partitions: int | None = ..., state_ttl_ms: int | None = ...) -> Session: ...
    def execute_local(self, *args: object, **kwargs: object) -> object: ...
    def execute_remote(self, *args: object, **kwargs: object) -> object: ...
    def flush_stream_job(self, *args: object, **kwargs: object) -> object: ...
    def from_bounded_stream(self, *args: object, **kwargs: object) -> object: ...
    @classmethod
    def from_env(cls) -> Session: ...
    def from_source(self, *args: object, **kwargs: object) -> object: ...
    def get_config(self, key: str) -> str | None: ...
    def is_streaming_query(self, *args: object, **kwargs: object) -> object: ...
    def ivm(self, name: str) -> IvmJob: ...
    def jobs(self) -> list[JobStatus]: ...
    def list_aggregate_udfs(self, *args: object, **kwargs: object) -> object: ...
    def list_table_identifiers(self) -> list[str]: ...
    def list_table_udfs(self, *args: object, **kwargs: object) -> object: ...
    def list_tables(self) -> list[str]: ...
    def list_udfs(self, *args: object, **kwargs: object) -> object: ...
    @classmethod
    def local(cls, *, target_parallelism: int | None = ..., shuffle_partitions: int | None = ..., state_ttl_ms: int | None = ...) -> Session: ...
    def memory_stream(self, *args: object, **kwargs: object) -> object: ...
    def memory_stream_collect(self, *args: object, **kwargs: object) -> object: ...
    @property
    def mode(self) -> RuntimeMode: ...
    def operation_registry(self, *args: object, **kwargs: object) -> object: ...
    def pipeline(self, *args: object, **kwargs: object) -> object: ...
    def prepare(self, sql: str) -> PreparedStatement: ...
    def read_csv(self, path: str) -> DataFrame: ...
    def read_csv_with_options(self, path: str, *, delimiter: str | None = ..., has_header: bool | None = ...) -> DataFrame: ...
    def read_file(self, path: str, format: DataFormat, *, header: bool = ..., delimiter: str = ...) -> DataFrame: ...
    def read_json(self, path: str) -> DataFrame: ...
    def read_parquet(self, path: str) -> DataFrame: ...
    def read_parquet_with_options(self, path: str, *, batch_size: int | None = ...) -> DataFrame: ...
    def read_state(self, *args: object, **kwargs: object) -> object: ...
    def read_stream(self, *args: object, **kwargs: object) -> object: ...
    def register_aggregate_udf(self, *args: object, **kwargs: object) -> object: ...
    def register_dataframe(self, *args: object, **kwargs: object) -> object: ...
    def register_function(self, *args: object, **kwargs: object) -> object: ...
    def register_kafka_source(self, *args: object, **kwargs: object) -> object: ...
    def register_kinesis_source(self, *args: object, **kwargs: object) -> object: ...
    def register_parquet(self, *args: object, **kwargs: object) -> object: ...
    def register_parquet_stream(self, *args: object, **kwargs: object) -> object: ...
    def register_pulsar_source(self, *args: object, **kwargs: object) -> object: ...
    def register_python_udaf_bytes(self, *args: object, **kwargs: object) -> object: ...
    def register_python_udf_bytes(self, *args: object, **kwargs: object) -> object: ...
    def register_record_batches(self, name: str, batches: Sequence[Batch]) -> None: ...
    def register_remote_parquet(self, *args: object, **kwargs: object) -> object: ...
    def register_scalar_sql_function(self, *args: object, **kwargs: object) -> object: ...
    def register_table_udf(self, *args: object, **kwargs: object) -> object: ...
    def register_udf(self, *args: object, **kwargs: object) -> object: ...
    def register_unbounded(self, *args: object, **kwargs: object) -> object: ...
    def register_unbounded_with_capacity(self, *args: object, **kwargs: object) -> object: ...
    def set_config(self, key: str, value: str) -> None: ...
    @classmethod
    def single_node(
        cls,
        url: str,
        *,
        grpc_url: str | None = ...,
        target_parallelism: int | None = ...,
        shuffle_partitions: int | None = ...,
        state_ttl_ms: int | None = ...,
    ) -> Session: ...
    def sql(self, query: str) -> DataFrame: ...
    def sql_as(self, query: str, api_key: str) -> DataFrame: ...
    async def sql_async(self, query: str) -> DataFrame: ...
    def sql_with_timeout(self, query: str, timeout_ms: int) -> DataFrame: ...
    def sql_with_timeout_async(self, *args: object, **kwargs: object) -> object: ...
    def stream(self, *args: object, **kwargs: object) -> object: ...
    def submit_async(self, query: str) -> QueryHandle: ...
    def submit_sql(self, *args: object, **kwargs: object) -> object: ...
    def submit_streaming_sql(self, *args: object, **kwargs: object) -> object: ...
    def table(self, name: str) -> DataFrame: ...
    def table_exists(self, name: str) -> bool: ...
    def table_metadata(self, name: str) -> object: ...
    def unset_config(self, key: str) -> None: ...
    def with_auth_token(self, *args: object, **kwargs: object) -> object: ...
    def with_oidc_provider(self, *args: object, **kwargs: object) -> object: ...
    def with_policy(self, *args: object, **kwargs: object) -> object: ...
    # ── grafted at import (see krishiv._pyspark) ──
    def createDataFrame(self, data: Any, schema: Any = ...) -> DataFrame: ...
    def range(self, start: int, end: int | None = ..., step: int = ..., numPartitions: int | None = ...) -> DataFrame: ...
    def stop(self) -> None: ...
    @property
    def udf(self) -> Any: ...
    @property
    def catalog(self) -> Any: ...
    @property
    def read(self) -> Any: ...
    @property
    def readStream(self) -> DataStreamReader: ...
    # The view's rows as of this call, and the entry point for composing
    # a derived incremental view.
    def view(self, iv: IncrementalDataFrame) -> DataFrame: ...
    builder: Any
    def is_embedded(self) -> bool: ...
    def is_single_node(self) -> bool: ...
    def is_distributed(self) -> bool: ...
    def register_arrow_stream(self, job_name: str, async_gen: AsyncIterator[Any]) -> None: ...

class StepSummary:
    def __repr__(self) -> str: ...
    @property
    def active_views(self) -> int: ...
    @property
    def degraded_views(self) -> list[str]: ...
    @property
    def errored_views(self) -> list[ViewError]: ...
    @property
    def tick(self) -> int: ...
    @property
    def total_output_rows(self) -> int: ...

class StreamWriter:
    def checkpoint(self, *args: object, **kwargs: object) -> object: ...
    def format(self, *args: object, **kwargs: object) -> object: ...
    def option(self, *args: object, **kwargs: object) -> object: ...
    def output_mode(self, *args: object, **kwargs: object) -> object: ...
    def parallelism(self, *args: object, **kwargs: object) -> object: ...
    def start(self, *args: object, **kwargs: object) -> object: ...
    def trigger(self, *args: object, **kwargs: object) -> object: ...

class StreamingDataFrame:
    def agg(self, *args: object, **kwargs: object) -> object: ...
    def broadcast_process(self, *args: object, **kwargs: object) -> object: ...
    def co_process(self, *args: object, **kwargs: object) -> object: ...
    def collect(self, *args: object, **kwargs: object) -> object: ...
    def drop_columns(self, *args: object, **kwargs: object) -> object: ...
    def drop_duplicates(self, *args: object, **kwargs: object) -> object: ...
    def drop_duplicates_with_state(self, *args: object, **kwargs: object) -> object: ...
    async def execute_stream_async(self) -> DataFrameStream: ...
    def execute_stream_with_side_output_async(self, *args: object, **kwargs: object) -> object: ...
    def filter(self, *args: object, **kwargs: object) -> object: ...
    def key_by(self, column: str) -> StreamingDataFrame: ...
    def select(self, *args: object, **kwargs: object) -> object: ...
    def session_window(self, gap_ms: int) -> StreamingDataFrame: ...
    def sliding_window(self, window_size_ms: int, slide_ms: int) -> StreamingDataFrame: ...
    def transform_with_state(self, *args: object, **kwargs: object) -> object: ...
    def tumbling_window(self, window_size_ms: int) -> StreamingDataFrame: ...
    def with_column(self, *args: object, **kwargs: object) -> object: ...
    def with_event_time(self, column: str) -> StreamingDataFrame: ...
    def with_side_output(self, *args: object, **kwargs: object) -> object: ...
    def with_source_id_column(self, *args: object, **kwargs: object) -> object: ...
    def with_source_watermark(self, *args: object, **kwargs: object) -> object: ...
    def with_state_ttl(self, *args: object, **kwargs: object) -> object: ...
    def with_watermark_lag(self, lag_ms: int) -> StreamingDataFrame: ...
    def write(self, *args: object, **kwargs: object) -> object: ...
    # ── grafted at import (see krishiv._pyspark) ──
    def withWatermark(self, eventTimeColumn: str, delayThreshold: str | int) -> StreamingDataFrame: ...
    def dropDuplicates(self, subset: Sequence[str] | None = ...) -> StreamingDataFrame: ...
    def keyBy(self, column: str) -> StreamingDataFrame: ...
    def tumblingWindow(self, duration: str | int) -> StreamingDataFrame: ...
    def slidingWindow(self, size: str | int, slide: str | int) -> StreamingDataFrame: ...
    def sessionWindow(self, gap: str | int) -> StreamingDataFrame: ...
    def where(self, condition: ColumnOrName) -> StreamingDataFrame: ...
    def withColumn(self, name: str, expr: ColumnOrName) -> StreamingDataFrame: ...
    def drop(self, *columns: str) -> StreamingDataFrame: ...
    def transformWithState(self, handler: object) -> StreamingDataFrame: ...

class StreamingJob:
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def attach(self, *args: object, **kwargs: object) -> object: ...
    def drain(self, *args: object, **kwargs: object) -> object: ...
    def flush(self, *args: object, **kwargs: object) -> object: ...
    def id(self, *args: object, **kwargs: object) -> object: ...
    def push(self, *args: object, **kwargs: object) -> object: ...
    def stop(self, *args: object, **kwargs: object) -> object: ...

class ValueState:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def clear(self, *args: object, **kwargs: object) -> object: ...
    def get_json(self, *args: object, **kwargs: object) -> object: ...
    def key(self, *args: object, **kwargs: object) -> object: ...
    def set_json(self, *args: object, **kwargs: object) -> object: ...

class ViewError:
    def __repr__(self) -> str: ...
    # 'operator_apply' | 'view_sql' | 'publish'
    @property
    def kind(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def view(self) -> str: ...

class WeaviateSink:
    def __init__(self, *args: object, **kwargs: object) -> object: ...
    def __repr__(self, *args: object, **kwargs: object) -> object: ...
    def delete_by_ids(self, *args: object, **kwargs: object) -> object: ...
    def query_nearest(self, *args: object, **kwargs: object) -> object: ...
    def sink_name(self, *args: object, **kwargs: object) -> object: ...
    def upsert_batch(self, *args: object, **kwargs: object) -> object: ...

def apply_async_io(*args: object, **kwargs: object) -> object: ...
def apply_process_function(*args: object, **kwargs: object) -> object: ...
def apply_state_migration(*args: object, **kwargs: object) -> object: ...
def avg(column: Column) -> Column: ...
def call_function(name: str, arguments: Sequence[Column]) -> Column: ...
def col(name: str) -> Column: ...
def connect_streaming(*args: object, **kwargs: object) -> object: ...
def count(column: Column) -> Column: ...
def count_all() -> Column: ...
def cume_dist() -> Column: ...
def dense_rank() -> Column: ...
def expr(sql: str) -> Column: ...
def first_value(column: Column) -> Column: ...
def interval_join(*args: object, **kwargs: object) -> object: ...
def lag(column: Column, offset: int = ..., default: ColumnLike | None = ...) -> Column: ...
def last_value(column: Column) -> Column: ...
def lead(column: Column, offset: int = ..., default: ColumnLike | None = ...) -> Column: ...
def lit(value: ColumnLike) -> Column: ...
def make_example_batch() -> Batch: ...
def max(column: Column) -> Column: ...
def memo_cache_info(*args: object, **kwargs: object) -> object: ...
def memo_transform_call(*args: object, **kwargs: object) -> object: ...
def min(column: Column) -> Column: ...
def nth_value(column: Column, n: int) -> Column: ...
def ntile(n: int) -> Column: ...
def percent_rank() -> Column: ...
def rank() -> Column: ...
def read_delta(*args: object, **kwargs: object) -> object: ...
def read_hudi(*args: object, **kwargs: object) -> object: ...
def read_iceberg(*args: object, **kwargs: object) -> object: ...
def read_kafka(*args: object, **kwargs: object) -> object: ...
def read_kinesis(*args: object, **kwargs: object) -> object: ...
def read_parquet(path: str) -> DataFrame: ...
def read_pulsar(*args: object, **kwargs: object) -> object: ...
def register_state_migration(*args: object, **kwargs: object) -> object: ...
def row_number() -> Column: ...
def schema_registry_confluent(*args: object, **kwargs: object) -> object: ...
def state_migration(*args: object, **kwargs: object) -> object: ...
def stream_table_join(*args: object, **kwargs: object) -> object: ...
def sum(column: Column) -> Column: ...
def temporal_join(*args: object, **kwargs: object) -> object: ...
def udf(*args: object, **kwargs: object) -> object: ...
def when(*args: object, **kwargs: object) -> object: ...
def write_delta(*args: object, **kwargs: object) -> object: ...
def write_hudi_append(*args: object, **kwargs: object) -> object: ...
def write_hudi_upsert(*args: object, **kwargs: object) -> object: ...
