"""Type stubs for the native ``krishiv`` extension module."""

from typing import Any, AsyncIterator, ClassVar, Optional, Tuple, overload

class KrishivError(Exception): ...
class QueryError(KrishivError): ...
class SchemaError(KrishivError): ...
class ConnectorError(KrishivError): ...
class CheckpointError(KrishivError): ...
class AuthorizationError(KrishivError): ...
class ModeError(KrishivError): ...

class Session:
    @classmethod
    def embedded(cls) -> Session: ...
    @classmethod
    def local(cls) -> Session: ...
    @classmethod
    def connect(cls, url: str) -> Session: ...
    @classmethod
    def from_env(cls) -> Session: ...
    @property
    def mode(self) -> str: ...
    def sql(self, query: str) -> DataFrame: ...
    def sql_async(self, query: str) -> DataFrame: ...
    def register_parquet(self, name: str, path: str) -> None: ...
    def stream(self, query: str, watermark_column: str, max_lateness_ms: int) -> Stream: ...

class DataFrame:
    def collect(self) -> str: ...
    def num_rows(self) -> int: ...

class Stream:
    def watermark(self, column: str, max_lateness_ms: int) -> WindowedStream: ...
    def with_watermark(self, column: str, max_lateness_ms: int) -> WindowedStream: ...
    def key_by(self, *columns: str) -> KeyedStream: ...
    def tumbling_window(self, window_secs: int) -> WindowedStream: ...
    def sink(self, sink: Any) -> None: ...

class KeyedStream:
    def with_watermark(self, column: str, max_lateness_ms: int) -> WindowedStream: ...
    def window(self, spec: Tuple[str, int]) -> WindowedStream: ...
    def tumbling_window(self, window_secs: int) -> WindowedStream: ...

class WindowedStream:
    def __aiter__(self) -> AsyncIterator[Batch]: ...
    def __anext__(self) -> Batch: ...
    def collect(self) -> list[Batch]: ...
    def tumbling_window(self, window_secs: int) -> WindowedStream: ...
    def agg(self, **kwargs: Any) -> WindowedStream: ...
    def sink(self, sink: Any) -> None: ...

class Batch:
    @property
    def num_rows(self) -> int: ...
    @property
    def num_columns(self) -> int: ...
    def to_arrow(self) -> Any: ...
    def to_pandas(self) -> Any: ...

class Schema:
    @classmethod
    def arrow_schema(cls) -> Any: ...

class ParquetSink:
    def __init__(self, path: str) -> None: ...

class KafkaSink:
    def __init__(self, topic: str, bootstrap_servers: str) -> None: ...

class IcebergSink:
    def __init__(self, catalog: str, table: str) -> None: ...

def read_parquet(path: str) -> DataFrame: ...
def read_kafka(session: Session, topic: str, bootstrap_servers: str) -> Stream: ...
