from typing import Any, Optional, Union

from ..krishiv import Column

ColumnOrName = Union[Column, str]
ColumnLike = Union[Column, str, None, bool, int, float, bytes]

def col(name: str) -> Column: ...
def column(name: str) -> Column: ...
def lit(value: Any) -> Column: ...
def expr(sql: str) -> Column: ...
def call_function(name: str, *args: ColumnLike) -> Column: ...
def function(name: str, *args: ColumnLike) -> Column: ...
def count(column: ColumnLike = "*") -> Column: ...
def count_all() -> Column: ...
def sum(column: ColumnOrName) -> Column: ...
def avg(column: ColumnOrName) -> Column: ...
def mean(column: ColumnOrName) -> Column: ...
def min(column: ColumnOrName) -> Column: ...
def max(column: ColumnOrName) -> Column: ...
def coalesce(*columns: ColumnLike) -> Column: ...
def ifnull(value: ColumnLike, replacement: ColumnLike) -> Column: ...
def nullif(left: ColumnLike, right: ColumnLike) -> Column: ...
def isnull(column: ColumnLike) -> Column: ...
def isnotnull(column: ColumnLike) -> Column: ...
def isnan(column: ColumnLike) -> Column: ...
def upper(column: ColumnLike) -> Column: ...
def lower(column: ColumnLike) -> Column: ...
def length(column: ColumnLike) -> Column: ...
def trim(column: ColumnLike) -> Column: ...
def ltrim(column: ColumnLike) -> Column: ...
def rtrim(column: ColumnLike) -> Column: ...
def concat(*columns: ColumnLike) -> Column: ...
def abs(column: ColumnLike) -> Column: ...
def round(column: ColumnLike, scale: Optional[int] = None) -> Column: ...
def floor(column: ColumnLike) -> Column: ...
def ceil(column: ColumnLike) -> Column: ...
def sqrt(column: ColumnLike) -> Column: ...
def exp(column: ColumnLike) -> Column: ...
def log(column: ColumnLike) -> Column: ...
def sin(column: ColumnLike) -> Column: ...
def cos(column: ColumnLike) -> Column: ...
def tan(column: ColumnLike) -> Column: ...
def current_date() -> Column: ...
def current_timestamp() -> Column: ...
def date_trunc(unit: str, timestamp: ColumnLike) -> Column: ...
def asc(column: ColumnLike) -> Column: ...
def desc(column: ColumnLike) -> Column: ...
def cast(column: ColumnLike, data_type: str) -> Column: ...
def try_cast(column: ColumnLike, data_type: str) -> Column: ...
