"""Type stubs for :mod:`krishiv.sql.functions` (auto-generated from the
runtime signatures — keep in sync with functions.py)."""

from typing import Any, Optional, Union

from ..krishiv import Column

ColumnOrName = Union[Column, str]
ColumnLike = Union[Column, str, None, bool, int, float, bytes]

def col(name: str) -> Column: ...
def column(name: str) -> Column: ...
def lit(value: Any) -> Column: ...
def expr(sql: str) -> Column: ...
def call_function(name: str, *args: ColumnLike) -> Column: ...
def function(name: str, *args: ColumnLike) -> Column: ...
def asc(column: ColumnLike) -> Column: ...
def desc(column: ColumnLike) -> Column: ...
def cast(column: ColumnLike, data_type: str) -> Column: ...
def try_cast(column: ColumnLike, data_type: str) -> Column: ...
def when(condition: Column, value: Any) -> Column: ...
def coalesce(*columns: ColumnLike) -> Column: ...
def ifnull(value: ColumnLike, replacement: ColumnLike) -> Column: ...
def nullif(left: ColumnLike, right: ColumnLike) -> Column: ...
def nvl(column: ColumnLike, replacement: ColumnLike) -> Column: ...
def nvl2(column: ColumnLike, value_if_not_null: ColumnLike, value_if_null: ColumnLike) -> Column: ...
def nanvl(col1: ColumnLike, col2: ColumnLike) -> Column: ...
def greatest(*columns: ColumnLike) -> Column: ...
def least(*columns: ColumnLike) -> Column: ...
def isnull(column: ColumnLike) -> Column: ...
def isnotnull(column: ColumnLike) -> Column: ...
def isnan(column: ColumnLike) -> Column: ...
def avg(column: ColumnOrName) -> Column: ...
def mean(column: ColumnOrName) -> Column: ...
def count(column: ColumnLike = '*') -> Column: ...
def count_all() -> Column: ...
def count_distinct(*columns: ColumnLike) -> Column: ...
def sum(column: ColumnOrName) -> Column: ...
def sum_distinct(column: ColumnOrName) -> Column: ...
def min(column: ColumnOrName) -> Column: ...
def max(column: ColumnOrName) -> Column: ...
def first(column: ColumnOrName) -> Column: ...
def last(column: ColumnOrName) -> Column: ...
def median(column: ColumnOrName) -> Column: ...
def stddev(column: ColumnOrName) -> Column: ...
def stddev_samp(column: ColumnOrName) -> Column: ...
def stddev_pop(column: ColumnOrName) -> Column: ...
def variance(column: ColumnOrName) -> Column: ...
def var_samp(column: ColumnOrName) -> Column: ...
def var_pop(column: ColumnOrName) -> Column: ...
def corr(col1: ColumnOrName, col2: ColumnOrName) -> Column: ...
def covar_samp(col1: ColumnOrName, col2: ColumnOrName) -> Column: ...
def covar_pop(col1: ColumnOrName, col2: ColumnOrName) -> Column: ...
def approx_count_distinct(column: ColumnOrName) -> Column: ...
def array_agg(column: ColumnOrName) -> Column: ...
def collect_list(column: ColumnOrName) -> Column: ...
def bit_and(column: ColumnOrName) -> Column: ...
def bit_or(column: ColumnOrName) -> Column: ...
def bit_xor(column: ColumnOrName) -> Column: ...
def bool_and(column: ColumnOrName) -> Column: ...
def bool_or(column: ColumnOrName) -> Column: ...
def upper(column: ColumnLike) -> Column: ...
def lower(column: ColumnLike) -> Column: ...
def length(column: ColumnLike) -> Column: ...
def char_length(column: ColumnLike) -> Column: ...
def octet_length(column: ColumnLike) -> Column: ...
def bit_length(column: ColumnLike) -> Column: ...
def trim(column: ColumnLike) -> Column: ...
def ltrim(column: ColumnLike) -> Column: ...
def rtrim(column: ColumnLike) -> Column: ...
def btrim(column: ColumnLike) -> Column: ...
def concat(*columns: ColumnLike) -> Column: ...
def concat_ws(sep: str, *columns: ColumnLike) -> Column: ...
def ascii(column: ColumnLike) -> Column: ...
def chr(column: ColumnLike) -> Column: ...
def initcap(column: ColumnLike) -> Column: ...
def reverse(column: ColumnLike) -> Column: ...
def repeat(column: ColumnLike, n: int) -> Column: ...
def instr(column: ColumnLike, substr: str) -> Column: ...
def locate(substr: str, column: ColumnLike, pos: int = 1) -> Column: ...
def lpad(column: ColumnLike, length: int, pad: str = ' ') -> Column: ...
def rpad(column: ColumnLike, length: int, pad: str = ' ') -> Column: ...
def left(column: ColumnLike, n: int) -> Column: ...
def right(column: ColumnLike, n: int) -> Column: ...
def substr(column: ColumnLike, pos: ColumnLike, length: Optional[ColumnLike] = None) -> Column: ...
def substring(column: ColumnLike, pos: int, length: int) -> Column: ...
def split_part(column: ColumnLike, delimiter: str, part: int) -> Column: ...
def translate(column: ColumnLike, matching: str, replacing: str) -> Column: ...
def starts_with(column: ColumnLike, prefix: ColumnLike) -> Column: ...
def ends_with(column: ColumnLike, suffix: ColumnLike) -> Column: ...
def contains(column: ColumnLike, substr: ColumnLike) -> Column: ...
def regexp_replace(column: ColumnLike, pattern: str, replacement: str) -> Column: ...
def regexp_like(column: ColumnLike, pattern: str) -> Column: ...
def abs(column: ColumnLike) -> Column: ...
def round(column: ColumnLike, scale: Optional[int] = None) -> Column: ...
def ceil(column: ColumnLike) -> Column: ...
def floor(column: ColumnLike) -> Column: ...
def sqrt(column: ColumnLike) -> Column: ...
def cbrt(column: ColumnLike) -> Column: ...
def exp(column: ColumnLike) -> Column: ...
def log(column: ColumnLike) -> Column: ...
def ln(column: ColumnLike) -> Column: ...
def log2(column: ColumnLike) -> Column: ...
def log10(column: ColumnLike) -> Column: ...
def power(base: ColumnLike, exponent: ColumnLike) -> Column: ...
def pow(base: ColumnLike, exponent: ColumnLike) -> Column: ...
def signum(column: ColumnLike) -> Column: ...
def sign(column: ColumnLike) -> Column: ...
def factorial(column: ColumnLike) -> Column: ...
def gcd(col1: ColumnLike, col2: ColumnLike) -> Column: ...
def lcm(col1: ColumnLike, col2: ColumnLike) -> Column: ...
def pi() -> Column: ...
def rand() -> Column: ...
def uuid() -> Column: ...
def sin(column: ColumnLike) -> Column: ...
def cos(column: ColumnLike) -> Column: ...
def tan(column: ColumnLike) -> Column: ...
def asin(column: ColumnLike) -> Column: ...
def acos(column: ColumnLike) -> Column: ...
def atan(column: ColumnLike) -> Column: ...
def atan2(y: ColumnLike, x: ColumnLike) -> Column: ...
def sinh(column: ColumnLike) -> Column: ...
def cosh(column: ColumnLike) -> Column: ...
def tanh(column: ColumnLike) -> Column: ...
def cot(column: ColumnLike) -> Column: ...
def degrees(column: ColumnLike) -> Column: ...
def radians(column: ColumnLike) -> Column: ...
def current_date() -> Column: ...
def current_timestamp() -> Column: ...
def now() -> Column: ...
def to_date(column: ColumnLike) -> Column: ...
def to_timestamp(column: ColumnLike) -> Column: ...
def date_trunc(unit: str, timestamp: ColumnLike) -> Column: ...
def year(column: ColumnLike) -> Column: ...
def month(column: ColumnLike) -> Column: ...
def day(column: ColumnLike) -> Column: ...
def dayofmonth(column: ColumnLike) -> Column: ...
def hour(column: ColumnLike) -> Column: ...
def minute(column: ColumnLike) -> Column: ...
def second(column: ColumnLike) -> Column: ...
def quarter(column: ColumnLike) -> Column: ...
def array(*columns: ColumnLike) -> Column: ...
def array_contains(column: ColumnLike, value: ColumnLike) -> Column: ...
def array_distinct(column: ColumnLike) -> Column: ...
def array_position(column: ColumnLike, value: ColumnLike) -> Column: ...
def array_remove(column: ColumnLike, value: ColumnLike) -> Column: ...
def array_append(column: ColumnLike, value: ColumnLike) -> Column: ...
def array_prepend(value: ColumnLike, column: ColumnLike) -> Column: ...
def array_union(col1: ColumnLike, col2: ColumnLike) -> Column: ...
def array_intersect(col1: ColumnLike, col2: ColumnLike) -> Column: ...
def array_except(col1: ColumnLike, col2: ColumnLike) -> Column: ...
def array_length(column: ColumnLike) -> Column: ...
def cardinality(column: ColumnLike) -> Column: ...
def flatten(column: ColumnLike) -> Column: ...
def explode(column) -> Any: ...
def posexplode(column) -> Any: ...
def md5(column: ColumnLike) -> Column: ...
def sha256(column: ColumnLike) -> Column: ...
def sha512(column: ColumnLike) -> Column: ...
def row_number() -> Column: ...
def rank() -> Column: ...
def dense_rank() -> Column: ...
def percent_rank() -> Column: ...
def cume_dist() -> Column: ...
def ntile(n: int) -> Column: ...
def lag(column: ColumnLike, offset: int = 1, default: ColumnLike = None) -> Column: ...
def lead(column: ColumnLike, offset: int = 1, default: ColumnLike = None) -> Column: ...
def first_value(column: ColumnLike) -> Column: ...
def last_value(column: ColumnLike) -> Column: ...
def nth_value(column: ColumnLike, n: int) -> Column: ...
