import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Badge, SiteShell } from '@/components/Shell';
import { docPages, getAllDocParams, getDoc } from '@/lib/docs-data';
import { docsVersions } from '@/lib/versions';

export default async function DocPage({params}:{params:Promise<{version:string;slug?:string[]}>}){const {version,slug}=await params;const page=getDoc(version,slug);if(!page)notFound();const idx=docPages.findIndex(p=>p.slug===page.slug);const prev=docPages[idx-1];const next=docPages[idx+1];return <SiteShell><main className="container docs-layout"><aside className="sidebar"><select className="version" defaultValue={version} aria-label="Documentation version">{docsVersions.map(v=><option key={v.slug} value={v.slug}>{v.label}</option>)}</select>{docPages.map(p=><Link key={p.slug} href={`/docs/${version}${p.slug?`/${p.slug}`:''}`}>{p.title}</Link>)}</aside><article className="docs-main"><Badge tone={page.status==='Available'?'green':page.status==='Experimental'?'violet':'blue'}>{page.status}</Badge><h1>{page.title}</h1><p className="lead">{page.description}</p>{page.body.map((b,i)=><p key={i}>{b}</p>)}<div className="card"><strong>Source-backed writing rule</strong><p className="muted">This page intentionally uses conservative wording from repository docs, examples, and public crate responsibilities. Expand examples only after validating current APIs.</p></div><div className="prevnext">{prev?<Link className="btn btn-secondary" href={`/docs/${version}${prev.slug?`/${prev.slug}`:''}`}>← {prev.title}</Link>:<span/>}{next?<Link className="btn btn-secondary" href={`/docs/${version}/${next.slug}`}>{next.title} →</Link>:<span/>}</div><p className="muted">Edit on GitHub placeholder: web/content/docs/{version}/{page.slug || 'index'}.mdx</p></article><aside className="toc"><strong>On this page</strong><a href="#top">Overview</a><a href="#status">Status</a><a href="#next">Next steps</a></aside></main></SiteShell>}
export function generateStaticParams(){return getAllDocParams()}
export async function generateMetadata({params}:{params:Promise<{version:string;slug?:string[]}>}){const {version,slug}=await params;const p=getDoc(version,slug);return p?{title:p.title,description:p.description}:{}}
