apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../crds/krishivjobs.yaml
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - operator-deployment.yaml
  - coordinator-deployment.yaml
  - coordinator-service.yaml
  - executor-deployment.yaml
  - sample-krishivjob.yaml
  - sample-streaming-krishivjob.yaml
