/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by Next.js in normal projects. It is checked in
// here so the web workspace can type-check before the first local dev run.
